config/routes.rb
ApprenticeFarmers::Application.routes.draw do
  resources :homes, :controller => 'home'

  resources :apprentices

  root :to => 'home#index'

end

app/models/apprentice.rb
class Apprentice < ActiveRecord::Base
end

app/models/home.rb
class Home < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/apprentices_controller.rb
class ApprenticesController < ApplicationController
  # GET /apprentices
  # GET /apprentices.json
  def index
    @apprentices = Apprentice.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @apprentices }
    end
  end

  # GET /apprentices/1
  # GET /apprentices/1.json
  def show
    @apprentice = Apprentice.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @apprentice }
    end
  end

  # GET /apprentices/new
  # GET /apprentices/new.json
  def new
    @apprentice = Apprentice.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @apprentice }
    end
  end

  # GET /apprentices/1/edit
  def edit
    @apprentice = Apprentice.find(params[:id])
  end

  # POST /apprentices
  # POST /apprentices.json
  def create
    @apprentice = Apprentice.new(params[:apprentice])

    respond_to do |format|
      if @apprentice.save
        format.html { redirect_to @apprentice, notice: 'Apprentice was successfully created.' }
        format.json { render json: @apprentice, status: :created, location: @apprentice }
      else
        format.html { render action: "new" }
        format.json { render json: @apprentice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /apprentices/1
  # PUT /apprentices/1.json
  def update
    @apprentice = Apprentice.find(params[:id])

    respond_to do |format|
      if @apprentice.update_attributes(params[:apprentice])
        format.html { redirect_to @apprentice, notice: 'Apprentice was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @apprentice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apprentices/1
  # DELETE /apprentices/1.json
  def destroy
    @apprentice = Apprentice.find(params[:id])
    @apprentice.destroy

    respond_to do |format|
      format.html { redirect_to apprentices_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apprentices_helper.rb
module ApprenticesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/apprentices/_form.html.erb
<%= form_for(@apprentice) do |f| %>
  <% if @apprentice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@apprentice.errors.count, "error") %> prohibited this apprentice from being saved:</h2>

      <ul>
      <% @apprentice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <strong>Contact Info</strong><br /><br />

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :street %><br />
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br />
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :gender %><br />
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.number_field :age %>
  </div>
  <br />
  <strong>Availability and Housing</strong><br /><br />

  Availability - Desired Working Dates*
  <br /><br />
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.date_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :room_and_board %><br />
    <%= f.number_field :room_and_board %>
  </div>
  <br />
  Willing to work at farms in the following counties*:
  <br /><br />
  <div class="field">
    <%= f.label :fairfield %><br />
    <%= f.check_box :fairfield %>
  </div>
  <div class="field">
    <%= f.label :hartford %><br />
    <%= f.check_box :hartford %>
  </div>
  <div class="field">
    <%= f.label :litchfield %><br />
    <%= f.check_box :litchfield %>
  </div>
  <div class="field">
    <%= f.label :middlesex %><br />
    <%= f.check_box :middlesex %>
  </div>
  <div class="field">
    New Haven<br />
    <%= f.check_box :newhaven %>
  </div>
  <div class="field">
    New London<br />
    <%= f.check_box :newlondon %>
  </div>
  <div class="field">
    <%= f.label :tolland %><br />
    <%= f.check_box :tolland %>
  </div>
  <div class="field">
    <%= f.label :windham %><br />
    <%= f.check_box :windham %>
  </div>
  <br />
  Would you be willing to go to a farm for an interview?
  <br /><br />
  <div class="field">
    Yes
    <%= f.check_box :interview %>
  </div>
  <br />
  Are you comfortable being the only apprentice on a farm?
  <br /><br />
  <div class="field">
    <%= f.label :only_apprentice %><br />
    <%= f.number_field :only_apprentice %>
  </div>
  <br />
  Explain any other details about your needs for housing, board, and willingness to travel to and from farms (For example, how far you would be willing to travel to a farm, flexibility about living at home or on-farm, etc.)
  <br /><br />
  <div class="field">
    <%= f.label :housing_details %><br />
    <%= f.text_area :housing_details %>
  </div>
  <br />
  My desired time commitment is:
  <br /><br />
  <div class="field">
    <%= f.label :commitment %><br />
    <%= f.number_field :commitment %>
  </div>
  <br />
  Please specify your desired schedule* (fulltime, living on farm, mornings only, weekend, weekdays, etc.)
  <br /><br />
  <div class="field">
    <%= f.label :schedule %><br />
    <%= f.text_area :schedule %>
  </div>
  <div class="field">
    Do you have your own means of transportation?<br />
    <%= f.check_box :transportation %>
  </div>
  <div class="field">
    Can you drive a manual transimssion?<br />
    <%= f.check_box :manual_transmission %>
  </div>
  <br />
  <strong>Farm Experience and Interest</strong><br /><br />
  <div class="field">
    Why are you seeking an apprenticeship on an organic farm in Connecticut?<br />
    <%= f.text_area :why_apprentice %>
  </div>
  <br />
  Choose the types of farms you are interested in working on:
  <br /><br />
  <div class="field">
    <%= f.label :csa %><br />
    <%= f.check_box :csa %>
  </div>
  <div class="field">
    <%= f.label :dairy %><br />
    <%= f.check_box :dairy %>
  </div>
  <div class="field">
    <%= f.label :diversified %><br />
    <%= f.check_box :diversified %>
  </div>
  <div class="field">
    <%= f.label :farm_to_institution %><br />
    <%= f.check_box :farm_to_institution %>
  </div>
  <div class="field">
    <%= f.label :field_crops %><br />
    <%= f.check_box :field_crops %>
  </div>
  <div class="field">
    <%= f.label :livestock %><br />
    <%= f.check_box :livestock %>
  </div>
  <div class="field">
    <%= f.label :orchard %><br />
    <%= f.check_box :orchard %>
  </div>
  <div class="field">
    <%= f.label :organic %><br />
    <%= f.check_box :organic %>
  </div>
  <div class="field">
    <%= f.label :upick %><br />
    <%= f.check_box :upick %>
  </div>
  <div class="field">
    <%= f.label :vegetables %><br />
    <%= f.check_box :vegetables %>
  </div>
  <div class="field">
    <%= f.label :community_farm %><br />
    <%= f.check_box :community_farm %>
  </div>
  <div class="field">
    <%= f.label :other %><br />
    <%= f.check_box :other %>
  </div>
  <div class="field">
    Please describe your farm experience:<br />
    <%= f.number_field :farm_experience %>
  </div>
  <div class="field">
    Provide a brief summary of your work experience, both paid and volunteer, on and off far, within the past 5-8 years<br />
    <%= f.text_area :work_experience %>
  </div>
  <div class="field">
    What has led you to want to work and/or learn on a farm?<br />
    <%= f.text_area :led_to_work %>
  </div>
  <div class="field">
    Explain your interest in being an apprentice and how this traning will fit into future plans.<br />
    <%= f.text_area :interest_in_apprentice %>
  </div>
  <div class="field">
    Are you prepared for a job that can require repetitive, uncomfortable and/or strenuous tasks? Discuss any challenging physical activity done in recent years. Please explain any relevant medical conditions, physical limitations, emotional or psychological issues that will affect your ability to do farm work.<br />
    <%= f.text_area :prepared %>
  </div>
  <div class="field">
    Use this space to tell potential host farmers more about yourself and what you bring to a working and living situation.<br />
    <%= f.text_area :what_you_bring %>
  </div>
  <div class="field">
    <%= f.label :references %><br />
    <%= f.text_area :references %>
  </div>
  <div class="field">
    <%= f.label :bedroom_sharing %><br />
    <%= f.check_box :bedroom_sharing %>
  </div>
  <div class="field">
    <%= f.label :bathroom_sharing %><br />
    <%= f.check_box :bathroom_sharing %>
  </div>
  <div class="field">
    <%= f.label :rooming_needs %><br />
    <%= f.text_area :rooming_needs %>
  </div>
  <div class="field">
    <%= f.label :smoker %><br />
    <%= f.check_box :smoker %>
  </div>
  <div class="field">
    <%= f.label :food_restrictions %><br />
    <%= f.text_area :food_restrictions %>
  </div>
  <div class="field">
    <%= f.label :three_things %><br />
    <%= f.text_area :three_things %>
  </div>
  <div class="field">
    <%= f.label :heard_about %><br />
    <%= f.text_area :heard_about %>
  </div>
  <div class="field">
    <%= f.label :ctnofa_member %><br />
    <%= f.check_box :ctnofa_member %>
  </div>
  <div class="field">
    <%= f.label :agreement_a %><br />
    <%= f.check_box :agreement_a %>
  </div>
  <div class="field">
    <%= f.label :agreement_b %><br />
    <%= f.check_box :agreement_b %>
  </div>
  <div class="field">
    <%= f.label :agreement_c %><br />
    <%= f.check_box :agreement_c %>
  </div>
  <div class="field">
    <%= f.label :agreement_d %><br />
    <%= f.check_box :agreement_d %>
  </div>
  <div class="field">
    <%= f.label :agreement_e %><br />
    <%= f.check_box :agreement_e %>
  </div>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/apprentices/edit.html.erb
<h1>Editing apprentice</h1>

<%= render 'form' %>

<%= link_to 'Show', @apprentice %> |
<%= link_to 'Back', apprentices_path %>

app/views/apprentices/index.html.erb
<h1>Listing apprentices</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Street</th>
    <th>City</th>
    <th>State</th>
    <th>Zip</th>
    <th>Phone</th>
    <th>Email</th>
    <th>Gender</th>
    <th>Age</th>
    <th>Start date</th>
    <th>End date</th>
    <th>Room and board</th>
    <th>Fairfield</th>
    <th>Hartford</th>
    <th>Litchfield</th>
    <th>Middlesex</th>
    <th>Newhaven</th>
    <th>Newlondon</th>
    <th>Tolland</th>
    <th>Windham</th>
    <th>Interview</th>
    <th>Only apprentice</th>
    <th>Housing details</th>
    <th>Commitment</th>
    <th>Schedule</th>
    <th>Transportation</th>
    <th>Manual transmission</th>
    <th>Why apprentice</th>
    <th>Csa</th>
    <th>Dairy</th>
    <th>Diversified</th>
    <th>Farm to institution</th>
    <th>Field crops</th>
    <th>Livestock</th>
    <th>Orchard</th>
    <th>Organic</th>
    <th>Upick</th>
    <th>Vegetables</th>
    <th>Community farm</th>
    <th>Other</th>
    <th>Farm experience</th>
    <th>Work experience</th>
    <th>Led to work</th>
    <th>Interest in apprentice</th>
    <th>Prepared</th>
    <th>What you bring</th>
    <th>References</th>
    <th>Bedroom sharing</th>
    <th>Bathroom sharing</th>
    <th>Rooming needs</th>
    <th>Smoker</th>
    <th>Food restrictions</th>
    <th>Three things</th>
    <th>Heard about</th>
    <th>Ctnofa member</th>
    <th>Agreement a</th>
    <th>Agreement b</th>
    <th>Agreement c</th>
    <th>Agreement d</th>
    <th>Agreement e</th>
    <th>Username</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @apprentices.each do |apprentice| %>
  <tr>
    <td><%= apprentice.first_name %></td>
    <td><%= apprentice.last_name %></td>
    <td><%= apprentice.street %></td>
    <td><%= apprentice.city %></td>
    <td><%= apprentice.state %></td>
    <td><%= apprentice.zip %></td>
    <td><%= apprentice.phone %></td>
    <td><%= apprentice.email %></td>
    <td><%= apprentice.gender %></td>
    <td><%= apprentice.age %></td>
    <td><%= apprentice.start_date %></td>
    <td><%= apprentice.end_date %></td>
    <td><%= apprentice.room_and_board %></td>
    <td><%= apprentice.fairfield %></td>
    <td><%= apprentice.hartford %></td>
    <td><%= apprentice.litchfield %></td>
    <td><%= apprentice.middlesex %></td>
    <td><%= apprentice.newhaven %></td>
    <td><%= apprentice.newlondon %></td>
    <td><%= apprentice.tolland %></td>
    <td><%= apprentice.windham %></td>
    <td><%= apprentice.interview %></td>
    <td><%= apprentice.only_apprentice %></td>
    <td><%= apprentice.housing_details %></td>
    <td><%= apprentice.commitment %></td>
    <td><%= apprentice.schedule %></td>
    <td><%= apprentice.transportation %></td>
    <td><%= apprentice.manual_transmission %></td>
    <td><%= apprentice.why_apprentice %></td>
    <td><%= apprentice.csa %></td>
    <td><%= apprentice.dairy %></td>
    <td><%= apprentice.diversified %></td>
    <td><%= apprentice.farm_to_institution %></td>
    <td><%= apprentice.field_crops %></td>
    <td><%= apprentice.livestock %></td>
    <td><%= apprentice.orchard %></td>
    <td><%= apprentice.organic %></td>
    <td><%= apprentice.upick %></td>
    <td><%= apprentice.vegetables %></td>
    <td><%= apprentice.community_farm %></td>
    <td><%= apprentice.other %></td>
    <td><%= apprentice.farm_experience %></td>
    <td><%= apprentice.work_experience %></td>
    <td><%= apprentice.led_to_work %></td>
    <td><%= apprentice.interest_in_apprentice %></td>
    <td><%= apprentice.prepared %></td>
    <td><%= apprentice.what_you_bring %></td>
    <td><%= apprentice.references %></td>
    <td><%= apprentice.bedroom_sharing %></td>
    <td><%= apprentice.bathroom_sharing %></td>
    <td><%= apprentice.rooming_needs %></td>
    <td><%= apprentice.smoker %></td>
    <td><%= apprentice.food_restrictions %></td>
    <td><%= apprentice.three_things %></td>
    <td><%= apprentice.heard_about %></td>
    <td><%= apprentice.ctnofa_member %></td>
    <td><%= apprentice.agreement_a %></td>
    <td><%= apprentice.agreement_b %></td>
    <td><%= apprentice.agreement_c %></td>
    <td><%= apprentice.agreement_d %></td>
    <td><%= apprentice.agreement_e %></td>
    <td><%= apprentice.username %></td>
    <td><%= apprentice.password %></td>
    <td><%= link_to 'Show', apprentice %></td>
    <td><%= link_to 'Edit', edit_apprentice_path(apprentice) %></td>
    <td><%= link_to 'Destroy', apprentice, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Apprentice', new_apprentice_path %>

app/views/apprentices/new.html.erb
<h1>Apprentice Signup</h1>

<%= render 'form' %>

<%= link_to 'Back', apprentices_path %>

app/views/apprentices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @apprentice.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @apprentice.last_name %>
</p>

<p>
  <b>Street:</b>
  <%= @apprentice.street %>
</p>

<p>
  <b>City:</b>
  <%= @apprentice.city %>
</p>

<p>
  <b>State:</b>
  <%= @apprentice.state %>
</p>

<p>
  <b>Zip:</b>
  <%= @apprentice.zip %>
</p>

<p>
  <b>Phone:</b>
  <%= @apprentice.phone %>
</p>

<p>
  <b>Email:</b>
  <%= @apprentice.email %>
</p>

<p>
  <b>Gender:</b>
  <%= @apprentice.gender %>
</p>

<p>
  <b>Age:</b>
  <%= @apprentice.age %>
</p>

<p>
  <b>Start date:</b>
  <%= @apprentice.start_date %>
</p>

<p>
  <b>End date:</b>
  <%= @apprentice.end_date %>
</p>

<p>
  <b>Room and board:</b>
  <%= @apprentice.room_and_board %>
</p>

<p>
  <b>Fairfield:</b>
  <%= @apprentice.fairfield %>
</p>

<p>
  <b>Hartford:</b>
  <%= @apprentice.hartford %>
</p>

<p>
  <b>Litchfield:</b>
  <%= @apprentice.litchfield %>
</p>

<p>
  <b>Middlesex:</b>
  <%= @apprentice.middlesex %>
</p>

<p>
  <b>Newhaven:</b>
  <%= @apprentice.newhaven %>
</p>

<p>
  <b>Newlondon:</b>
  <%= @apprentice.newlondon %>
</p>

<p>
  <b>Tolland:</b>
  <%= @apprentice.tolland %>
</p>

<p>
  <b>Windham:</b>
  <%= @apprentice.windham %>
</p>

<p>
  <b>Interview:</b>
  <%= @apprentice.interview %>
</p>

<p>
  <b>Only apprentice:</b>
  <%= @apprentice.only_apprentice %>
</p>

<p>
  <b>Housing details:</b>
  <%= @apprentice.housing_details %>
</p>

<p>
  <b>Commitment:</b>
  <%= @apprentice.commitment %>
</p>

<p>
  <b>Schedule:</b>
  <%= @apprentice.schedule %>
</p>

<p>
  <b>Transportation:</b>
  <%= @apprentice.transportation %>
</p>

<p>
  <b>Manual transmission:</b>
  <%= @apprentice.manual_transmission %>
</p>

<p>
  <b>Why apprentice:</b>
  <%= @apprentice.why_apprentice %>
</p>

<p>
  <b>Csa:</b>
  <%= @apprentice.csa %>
</p>

<p>
  <b>Dairy:</b>
  <%= @apprentice.dairy %>
</p>

<p>
  <b>Diversified:</b>
  <%= @apprentice.diversified %>
</p>

<p>
  <b>Farm to institution:</b>
  <%= @apprentice.farm_to_institution %>
</p>

<p>
  <b>Field crops:</b>
  <%= @apprentice.field_crops %>
</p>

<p>
  <b>Livestock:</b>
  <%= @apprentice.livestock %>
</p>

<p>
  <b>Orchard:</b>
  <%= @apprentice.orchard %>
</p>

<p>
  <b>Organic:</b>
  <%= @apprentice.organic %>
</p>

<p>
  <b>Upick:</b>
  <%= @apprentice.upick %>
</p>

<p>
  <b>Vegetables:</b>
  <%= @apprentice.vegetables %>
</p>

<p>
  <b>Community farm:</b>
  <%= @apprentice.community_farm %>
</p>

<p>
  <b>Other:</b>
  <%= @apprentice.other %>
</p>

<p>
  <b>Farm experience:</b>
  <%= @apprentice.farm_experience %>
</p>

<p>
  <b>Work experience:</b>
  <%= @apprentice.work_experience %>
</p>

<p>
  <b>Led to work:</b>
  <%= @apprentice.led_to_work %>
</p>

<p>
  <b>Interest in apprentice:</b>
  <%= @apprentice.interest_in_apprentice %>
</p>

<p>
  <b>Prepared:</b>
  <%= @apprentice.prepared %>
</p>

<p>
  <b>What you bring:</b>
  <%= @apprentice.what_you_bring %>
</p>

<p>
  <b>References:</b>
  <%= @apprentice.references %>
</p>

<p>
  <b>Bedroom sharing:</b>
  <%= @apprentice.bedroom_sharing %>
</p>

<p>
  <b>Bathroom sharing:</b>
  <%= @apprentice.bathroom_sharing %>
</p>

<p>
  <b>Rooming needs:</b>
  <%= @apprentice.rooming_needs %>
</p>

<p>
  <b>Smoker:</b>
  <%= @apprentice.smoker %>
</p>

<p>
  <b>Food restrictions:</b>
  <%= @apprentice.food_restrictions %>
</p>

<p>
  <b>Three things:</b>
  <%= @apprentice.three_things %>
</p>

<p>
  <b>Heard about:</b>
  <%= @apprentice.heard_about %>
</p>

<p>
  <b>Ctnofa member:</b>
  <%= @apprentice.ctnofa_member %>
</p>

<p>
  <b>Agreement a:</b>
  <%= @apprentice.agreement_a %>
</p>

<p>
  <b>Agreement b:</b>
  <%= @apprentice.agreement_b %>
</p>

<p>
  <b>Agreement c:</b>
  <%= @apprentice.agreement_c %>
</p>

<p>
  <b>Agreement d:</b>
  <%= @apprentice.agreement_d %>
</p>

<p>
  <b>Agreement e:</b>
  <%= @apprentice.agreement_e %>
</p>

<p>
  <b>Username:</b>
  <%= @apprentice.username %>
</p>

<p>
  <b>Password:</b>
  <%= @apprentice.password %>
</p>


<%= link_to 'Edit', edit_apprentice_path(@apprentice) %> |
<%= link_to 'Back', apprentices_path %>

app/views/global/_header.html.erb
<header class="span12">
  <div class="row">
    <div class="span9">
      <ul class="nav nav-pills">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="#">Farms</a></li>
        <li><a href="#">FAQ</a></li>
        <li><a href="#">Contact Us</a></li>
        <li><a href="#">What to Expect</a></li>
      </ul>
    </div>
  </div>
</header>

app/views/home/index.html.erb
<article class="grid_9">
  <header>article header</header>
  <section>article content</section>
  <footer>article footer</footer>
</article>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page.title || @home.title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<<<<<<< HEAD
<body>
<%= image_tag("ctnofa_logo.jpg") %>
<%= yield %>
=======
<body class="container">

  <header class="row">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <nav><% render partial: 'shared/nav' %></nav>
    <%= yield :header %>
  </header>

  <aside>
    <%= yield :sidebar %>
  </aside>

  <div role="main">
    <%= yield %>
  </div>

  <footer class="row">
    <%= render partial: 'shared/footer' %>
  </footer>
>>>>>>> a7bd54c407fe2857012c1c86f5d1b341d1ab0287

</body>
</html>

app/views/shared/_footer.html.erb
<footer class="grid_12">
  <nav>
    <ul>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
    </ul>
  </nav>
</footer>

app/views/shared/_nav.html.erb
<header class="span12">
  <div class="row">
    <div class="span9">
      <ul class="nav nav-pills">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="#">Farms</a></li>
        <li><a href="#">FAQ</a></li>
        <li><a href="#">Contact Us</a></li>
        <li><a href="#">What to Expect</a></li>
      </ul>
    </div>
  </div>
</header>

app/views/shared/_sidebar.html.erb
<aside class="grid_3">
  <nav>
    <ul>
      <li>the</li>
      <li>side</li>
      <li>bar</li>
    </ul>
  </nav>
</aside>